# Default values for omar-wfs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

appName: omar-wfs

global:
  dockerRepository: nexus-docker-private-group.ossim.io
  imagePullSecret:
    registry: null
    username: null
    password: null
  hostname: omar-dev.ossim.io

  omarDb:
    name: null
    host: null
    user: null
    password: null
    port: null

  ingress:
    class: nginx
    enabled: true
    annotations: {}

  useTls: false
  useTLSClientAuth: false
  sslCertSecretName: null
  authSslCertSecretName: null

  createImagePullSecret: true
  useImagePullSecret: true

  autoscaling:
    enabled: true

  useSpringConfigServer: false

# These variables can be overridden because of the use of the 'pluck' function:
# - createIngress
# - useTls
# - useTlsClientAuth
# - createImagePullSecret
# - createHpa
# - createPVs
# - useSpringConfigServer

resources:
  limits:
    cpu: 1500m
    memory: 1000Mi
  requests:
    cpu: 500m
    memory: 500Mi

autoscaling:
  enabled:
  # targetCpu: 50
  minReplicas: 1
  maxReplicas: 1

image:
  name: omar-wfs
  tag: null
  pullPolicy: IfNotPresent

ingress:
  enabled:
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  class: # defaults to nginx if not set

path: /omar-wfs
internalPort: 8080
externalPort: 8080

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

readinessProbe:
  failureThreshold: 15
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3
  path: /omar-wfs/actuator/health

terminationGracePeriodSeconds: 30

# envVars:
#   SPRING_CLOUD_CONFIG_LABEL: master

configmaps: {}

extraInitContainers: []

sideCars: []
