{{- $annotations := merge .Values.deployment.annotations $.Values.global.deployment.annotations -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "omar-wfs.labels" . | nindent 4 }}
  name: {{ include "omar-wfs.fullname" . }}
  annotations:
  {{- range $key, $value := $annotations }}
    {{- $key | nindent 4 }}: {{ tpl $value $ | quote }}
  {{- end }}
spec:
  {{- if eq (include "omar-wfs.autoscaling.enabled" $) "false" }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "omar-wfs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "omar-wfs.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: wait-for-geoscript
        image: "{{ .Values.global.image.registry }}/busybox:1.28"
        command: ['sh', '-c', "until nslookup omar-geoscript; do echo waiting for geoscript; sleep 2; done"]
      {{- if .Values.extraInitContainers }}
      {{- toYaml .Values.extraInitContainers | nindent 6 }}
      {{- end }}
      containers:
      {{- if .Values.sideCars }}
      {{- toYaml .Values.sideCars | nindent 6 }}
      {{- end }}
      - name: {{ .Chart.Name }}
        env:
        {{- include "omar-wfs.envVars" . | nindent 8 }}
        envFrom:
          {{- with (concat .Values.envFrom .Values.global.envFrom) }}
          {{- tpl (toYaml .) $ | nindent 10 }}
          {{- end }}
        image: {{ include "omar-wfs.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          tcpSocket:
            port: {{ .Values.internalPort }}
        readinessProbe:
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.internalPort }}
            scheme: HTTP
        ports:
        - containerPort: {{ .Values.internalPort }}
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          {{- include "omar-wfs.volumeMounts" . | nindent 12 }}
      dnsPolicy: ClusterFirst
      {{- include "omar-wfs.imagePullSecrets" . | indent 6 }}
      restartPolicy: Always
      securityContext: {}
      serviceAccountName: {{ include "omar-wfs.serviceAccount.name" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with merge .Values.nodeSelector .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with merge .Values.affinity .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with concat .Values.tolerations .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- include "omar-wfs.volumes" . | nindent 8 }}
