apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-wfs-app
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-wfs-app
  uid: dc98eba7-82c2-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '8863882'
  generation: 263
  creationTimestamp: '2017-08-16T20:38:29Z'
  labels:
    app: omar-openshift
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-wfs-app
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-wfs-app:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-wfs-app@sha256:7612ab0efc09ce827732e2110a2ab0c254d709ec36a4411002a0b06779af0e52
  replicas: 1
  test: false
  selector:
    app: omar-openshift
    deploymentconfig: omar-wfs-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-openshift
        deploymentconfig: omar-wfs-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: volume-wfs
          persistentVolumeClaim:
            claimName: ossim-data-dev-pvc
      containers:
        - name: omar-wfs-app
          image: >-
            172.30.181.173:5000/o2/omar-wfs-app@sha256:7612ab0efc09ce827732e2110a2ab0c254d709ec36a4411002a0b06779af0e52
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
          resources: {}
          volumeMounts:
            - name: volume-wfs
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 253
  observedGeneration: 263
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-wfs-app:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-11-13T19:48:27Z'
      lastTransitionTime: '2017-11-13T19:48:27Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-11-30T12:34:44Z'
      lastTransitionTime: '2017-11-30T12:34:42Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-wfs-app-253" successfully rolled out
  readyReplicas: 1
